server:
  port: 0

# LOGGING
logging:
  path: log
  file: log/application.log
# levels for loggers, e.g. "logging.level.org.springframework=DEBUG" (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
  level.org.springframework: INFO

# eureka server registration
# register with eureka

eureka:
   instance:
    hostname: 52.7.102.164
   client:
    serviceUrl:
      defaultZone: http://52.7.102.164:8787/eureka/
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


